#+TITLE:     C++ Development Environment

* CC Mode

#+BEGIN_SRC emacs-lisp
  (use-package cc-mode
    :ensure nil
    :init
    (defun bw/cc-mode-hook()
      (c-set-style "stroustrup")
      (c-set-offset 'inline-open 0)
      ;; 将 _ 作为 Word 的一部分，这样 Evil 的 Word 相关命令能够正常工作
      (modify-syntax-entry ?_ "w"))

    (add-hook 'c-mode-common-hook 'bw/cc-mode-hook))
#+END_SRC

* Semantic

  Semantic 是 CEDET 的一部分，以 Emacs Lisp 实现各语言的解析器，从而提
供代码补全、代码浏览等功能的支持。
  - Company 自带 company-semantic 后端使用 Semantic 数据进行补全
  - Senator 使用 Semantic 数据进行代码浏览，也有代码补全功能

  Semantic 缺省自动解析有限的系统 INCLUDE 目录，具体内置可以查看变量
semantic-dependency-system-include-path。对于其他系统或第三方库的头文
件的路径，需要通过 semanntic-add-system-include 命令添加。

#+BEGIN_SRC emacs-lisp-example
  (semantic-add-system-include "~/kernel") ; 用于 C/C++ Modes
  (semantic-add-system-include "/usr/include/boost" 'c++-mode) ; 用于 C++ Mode
#+END_SRC

#+BEGIN_SRC emacs-lisp-example
  (setq semanticdb-default-save-directory
        (locate-user-emacs-file ".semanticdb"))

  (require 'semantic)

  ;; 将 Semantic 解析后的数据缓存到文件中
  (global-semanticdb-minor-mode 1)

  ;; 在用户不操作是自动更新数据，否则只在执行某些命令时更新
  (global-semantic-idle-scheduler-mode 1)

  ;; 激活 Semantic Mode，解析文件
  (semantic-mode 1)

  ;; 在 buffer 的第一行显示当前光标所在函数的函数名
  (add-to-list 'semantic-default-submodes
               'global-semantic-stickyfunc-mode)
#+END_SRC

* Flycheck - Syntax checking for GNU Emacs

  [[http://www.flycheck.org/][Flycheck]] 是个现代的实时语法检查工具，可以替代 Flymake。

#+BEGIN_SRC emacs-lisp
  (use-package flycheck
    :ensure t
    :init (global-flycheck-mode))
#+END_SRC

* cmake-font-lock

  [[https://github.com/Lindydancer/cmake-font-lock][cmake-font-lock]] 为 CMakeLists.txt 提供了语法高亮。

#+BEGIN_SRC emacs-lisp
  (use-package cmake-font-lock
    :ensure t
    :init
    (add-hook 'cmake-mode-hook 'cmake-font-lock-activate))
#+END_SRC

* bison-mode

  bison-mode 为 bison、yacc 和 lex 等文件提供了支持。

#+BEGIN_SRC emacs-lisp
  (use-package bison-mode
    :ensure t)
#+END_SRC

* Debugging

#+BEGIN_SRC emacs-lisp
  (setq
   ;; 缺省激活 gdb-many-windows
   gdb-many-windows t

   ;; 启动的时候显示包含 main 的源文件
   gdb-show-main t)
#+END_SRC

* 参考资料

  - [[https://tuhdo.github.io/c-ide.html][Setup C/C++ Development Environment for Emacs]]
  - [[https://github.com/mawenbao/emacs.d][awenbao/emacs.d]] 以上文为基础配置的 C/C++、Golang 和 Python 的开发
    环境
  - [[https://vxlabs.com/2016/04/11/step-by-step-guide-to-c-navigation-and-completion-with-emacs-and-the-clang-based-rtags/][C++ navigation and completion with Emacs and the Clang-based rtags]]
  - [[https://github.com/redguardtoo/mastering-emacs-in-one-year-guide/blob/master/emacs_cpp_developer_guide-en.org][Practical Emacs Guide for C++ developers]]
  - [[http://nilsdeppe.com/posts/emacs-c%2B%2B-ide][Using Emacs as a C++ IDE]]
  - [[https://github.com/emacs-tw/awesome-emacs][Awesome Emacs]] 推荐的扩展
    - CC Mode
    - rtags :: 基于 Clang 的 Tag
    - ggtags
    - irony-mode :: 基于 Clang 的补全
    - cmake-font-lock
    - function-args
    - Ebrowse
  - Spacemacs 使用的扩展
    - flycheck
    - disaster
    - clang-format :: 基于 Clang 的格式化
    - Semantic
    - cscope
    - company-clang
    - company-ycmd

