#+TITLE:     C++ Development Environment

* CC Mode

#+BEGIN_SRC emacs-lisp
  (use-package cc-mode
    :ensure nil
    :mode ("\\.h\\'" . c++-mode)
    :init
    (defun bw/cc-mode-hook()
      (c-set-style "stroustrup")
      (c-set-offset 'inline-open 0)
      ;; 将 _ 作为 Word 的一部分，这样 Evil 的 Word 相关命令能够正常工作
      (modify-syntax-entry ?_ "w"))

    (add-hook 'c-mode-common-hook 'bw/cc-mode-hook))
#+END_SRC

* Semantic

  Semantic 是 CEDET 的一部分，以 Emacs Lisp 实现各语言的解析器，从而提
供代码补全、代码浏览等功能的支持。
  - Company 自带 company-semantic 后端使用 Semantic 数据进行补全
  - Senator 使用 Semantic 数据进行代码浏览，也有代码补全功能

  Semantic 缺省自动解析有限的系统 INCLUDE 目录，具体内置可以查看变量
semantic-dependency-system-include-path。对于其他系统或第三方库的头文
件的路径，需要通过 semanntic-add-system-include 命令添加。

#+BEGIN_SRC emacs-lisp-example
  (semantic-add-system-include "~/kernel") ; 用于 C/C++ Modes
  (semantic-add-system-include "/usr/include/boost" 'c++-mode) ; 用于 C++ Mode
#+END_SRC

#+BEGIN_SRC emacs-lisp-example
  (setq semanticdb-default-save-directory
        (locate-user-emacs-file ".semanticdb"))

  (require 'semantic)

  ;; 将 Semantic 解析后的数据缓存到文件中
  (global-semanticdb-minor-mode 1)

  ;; 在用户不操作是自动更新数据，否则只在执行某些命令时更新
  (global-semantic-idle-scheduler-mode 1)

  ;; 激活 Semantic Mode，解析文件
  (semantic-mode 1)

  ;; 在 buffer 的第一行显示当前光标所在函数的函数名
  (add-to-list 'semantic-default-submodes
               'global-semantic-stickyfunc-mode)
#+END_SRC

* CMake
** cmake-font-lock

  [[https://github.com/Lindydancer/cmake-font-lock][cmake-font-lock]] 为 CMakeLists.txt 提供了语法高亮。

#+BEGIN_SRC emacs-lisp
  (use-package cmake-font-lock
    :ensure t
    :init
    (add-hook 'cmake-mode-hook 'cmake-font-lock-activate))
#+END_SRC

** cmake-project

  Emacs 的 compile 命令缺省使用 Makefile，而 [[http://github.com/alamaison/emacs-cmake-project][cmake-project]] 让 compile
命令支持 CMake。

  使用 cmake-project 的方法。
  - M-x cmake-project-mode 启用 cmake-project
  - M-x cmake-project-configure-project 生成构建文件
  - M-x compile 进行构建

#+BEGIN_SRC emacs-lisp
  (use-package cmake-project
    :ensure t
    :init
    (defun bw/maybe-cmake-project-hook ()
      (if (file-exists-p "CMakeLists.txt") (cmake-project-mode)))
    (add-hook 'c-mode-common-hook 'bw/maybe-cmake-project-hook)
    :config
    (setq cmake-project-default-build-dir-name "build/"))
#+END_SRC

** cmake-ide

  [[https://github.com/atilaneves/cmake-ide][cmake-ide]] 不是 IDE，而是通过 CMakeLists.txt 或者 [[http://clang.llvm.org/docs/JSONCompilationDatabase.html][JSON Compilation
Database]]，为其他“IDE”扩展提供数据支持。cmake-ide 支持的扩展有：
  - auto-complete-clang
  - company-clang
  - company-c-headers
  - irony
  - semantic
  - flycheck
  - rtags

  分析 cmake-ide-run-cmake 的源代码，可以看到 cmake-ide 的原理是自动在
系统临时目录（或者 cmake-ide-build-dir 设置的目录）下调用 CMake，生成
[[http://clang.llvm.org/docs/JSONCompilationDatabase.html][JSON Compilation Database]] 文件，从中读取编译参数，然后为其他扩展设置必
要的信息。这个过程可以在 *Message* Buffer 看到一些的消息。

  具体地说，先是 cmake-ide--cdb-json-file-to-idb 从 JSON Compilation
Databae 读取信息转为 idb。然后在 cmake-ide--set-flags-for-file 中，调
用 cmake-ide--idb-file-to-obj 根据当前 Buffer 的文件名，从 idb 中查表
得到编译信息，然后调用 cmake-ide-set-compiler-flags 设置信息。

  分析 cmake-ide-set-compiler-flags 的源代码，可以看到 cmake-ide 是如
何为其他扩展设置信息的。
  - auto-complete-clang :: 设置 ac-clang-flags
  - company-clang :: 设置 company-clang-arguments
  - company-c-headers :: 设置 company-c-headers-path-user 和
       company-c-headers-path-system
  - irony :: 调用 irony-cdb-json-add-compile-commands-path 传入项目根
             目录和 JSON Compilation Database 路径，让 Irony 自己读取
             信息
  - semantic :: 通过 semantic-add-system-include 和
                semantic-remove-system-include 设置 Include Path
  - flycheck :: 设置 flycheck-clang-include-path 等

  在 Windows 环境，如果使用单独安装的 CMake 而且系统有安装 Visual
Studio， CMake 缺省生成 Visual C++ 的项目文件，这时没有 JSON
Compilation Database 生成，cmake-ide 就不能工作了。解决方法是使用
Cygwin 里的 CMake。另外，cmake-ide 有 cmake-ide-cmake-opts 变量，也许
可以通过这个变量设置使用 GCC 或 Clang，

#+BEGIN_SRC emacs-lisp
  (use-package cmake-ide
    :ensure t
    :init
    ;; 在 ~/.cmake-ide 目录下运行 CMake，而不是系统临时目录
    (setq cmake-ide-build-pool-dir (locate-user-emacs-file ".cmake-ide/"))
    ;; CMake 构建目录使用固定的名字，从而可以重用
    (setq cmake-ide-build-pool-use-persistent-naming t)
    ;; 将 cmake-ide--mode-hook 加到 C/C++ Mode Hook
    (cmake-ide-setup)
    :config
    (setq cmake-ide-flags-c++ (append '("-std=c++11")))
    (unless (file-directory-p cmake-ide-build-pool-dir)
      (make-directory cmake-ide-build-pool-dir))
    ;; Windows 平台的补丁
    (when bw/windows-p
      ;; cmake-ide 使用固定名字的构建目录时，是根据项目的绝对路径转成目
      ;; 录名的，在 Windows 平台要把冒号 : 替换成下划线 _
      (defadvice cmake-ide--get-project-key (after cleanup-colon act)
        (setq ad-return-value (replace-regexp-in-string ":" "_" ad-return-value)))
      (ad-activate 'cmake-ide--get-project-key)
      ;; 使用 Cygwin 的 CMake 时，将项目路径以绝对路径传给 CMake 时应该
      ;; 使用 Cygwin 风格，否则 CMake 会报错： Found relative path while
      ;; evaluating include directories of ...
      (defadvice cmake-ide--run-cmake-impl (before cygpath-conv (project-dir cmake-dir))
        (ad-set-arg 0 (bw/winpath-to-cygpath project-dir)))
      (ad-activate 'cmake-ide--run-cmake-impl)
      (defadvice cmake-ide--idb-file-to-obj (before cygpath-conv (idb file-name))
        (ad-set-arg 1 (bw/winpath-to-cygpath file-name)))
      (ad-activate 'cmake-ide--idb-file-to-obj)
      ;; cmake-ide--flags-to-include-paths 里调用 expand-file-name 时会
      ;; 将 /cygdrive/c/path 扩展为 c:/cygdrive/c/path
      (defun bw/preprocess-cmake-ide-flags (flags)
        (list (bw/use-winpath-in-list (car flags))))
      (advice-add 'cmake-ide--flags-to-include-paths :filter-args
                  #'bw/preprocess-cmake-ide-flags)))
#+END_SRC

* 补全
** irony

  [[https://github.com/Sarcasm/irony-mode][irony]] 以 Server/Client 模式，为 C/C++ 开发的代码补全、语法检查、
eldoc 等功能提供基础支持。Server 是基于 libclang 开发的程序，Client 是
Emacs 扩展。

  irony 扩展自带用 C++ 实现的服务端程序 irony-server 的代码
（irony/server），在第一次使用的时候要通过 irony-install-server 命令编
译安装。下面是相应的命令行，可以先手工编译、安装好。

#+BEGIN_SRC sh
  cmake -DCMAKE_INSTALL_PREFIX=~/.emacs.d/irony ~/.emacs.d/.elpa/irony/server
  cmake --build . --use-stderr --config Release --target install
#+END_SRC

  irony-server 安装后，可以在命令行下交互使用，下面是一些例子。

#+BEGIN_SRC sh
  # 启动 irony-server 交互界面
  irony-server -i
  # 补全指定文件的指定位置
  complete /path/to/file.cpp 7 8
  # 可以加额外的参数
  complete /path/to/file.cpp 7 8 -- -I/path/to/include
  # 查看补全选项
  candidates "" exact
  # 输出分析信息
  diagnostics
#+END_SRC

  irony 需要支持 C/C++ 文件的编译选项才能正常工作，这些信息可以通过
[[http://clang.llvm.org/docs/JSONCompilationDatabase.html][JSON Compilation Database]] 或 [[https://github.com/Rip-Rip/clang_complete/blob/c8673142759b87316265eb0edd1f620196ec1fba/doc/clang_complete.txt#L55][.clang_complete]] 提供。下面是一个用 CMake
生成的 JSON Compilation Database 的例子。

#+BEGIN_SRC javascript
  [
      {
          "directory": "/path/to/cmake/build/directory",
          "command": "/usr/bin/c++.exe -I/path/to/include -o CMakeFiles/example.dir/example.cpp.o -c /path/to/exmaple.cpp",
          "file": "/path/to/example.cpp"
      }
  ]
#+END_SRC

  M-x irony-cdb-json-add-compile-commands-path 从指定 JSON Compilation
Database 读取信息。

  如果编译信息被正确读取和设置了，可以在 irony--compile-options 中查看。
另外，变量 irony--working-directory 也在同时被设置。

#+BEGIN_SRC emacs-lisp
  (use-package irony
    :ensure t
    :init
    (add-hook 'c++-mode-hook 'irony-mode)
    (add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options)
    (setq irony-server-install-prefix
          (locate-user-emacs-file ".irony"))
    (setq irony-user-dir
          (locate-user-emacs-file ".irony/"))
    :config
    ;; Windows 平台补丁
    (when bw/windows-p
      (defun bw/preprocess-irony-server-send-command (args)
        (message "irony--server-send-command> %S" args)
        ;; 删掉 complete 命令最后一个参数（当前文件，在第一个参数也出现），
        ;; 否则 libclang 提示解析错误，不清楚是什么原因
        (if (string= "complete" (car args))
            (nbutlast args 1))
        (bw/use-cygpath-in-list args))
      (advice-add 'irony--server-send-command :filter-args #'bw/preprocess-irony-server-send-command))
    ;; 输出一些日志信息，便于分析
    (defadvice irony-iotask-send-string (before log-me (string))
      (setq inhibit-message t)
      (message "irony-iotask-send-string> %s" string)
      (setq inhibit-message nil))
    (ad-activate 'irony-iotask-send-string)
    (defadvice irony-cdb-json-add-compile-commands-path (before log-me
                                                                (project-root
                                                                 compile-commands-path))
      (message "irony-cdb-json-add-compile-commands-path> %s %s" project-root
               compile-commands-path))
    (ad-activate 'irony-cdb-json-add-compile-commands-path)
    (defun bw/log-irony-iotask-process-filter (process output)
      (setq inhibit-message t)
      (message "irony-iotask-process-filter> %s" output)
      (setq inhibit-message nil))
    (advice-add 'irony-iotask-process-filter :before #'bw/log-irony-iotask-process-filter)
    ;; Windows performance tweaks
    (when (boundp 'w32-pipe-read-delay)
      (setq w32-pipe-read-delay 0))
    ;; Set the buffer size to 64K on Windows (from the original 4K)
    (when (boundp 'w32-pipe-buffer-size)
      (setq irony-server-w32-pipe-buffer-size (* 64 1024))))
#+END_SRC

** company-irony

  [[https://github.com/Sarcasm/company-irony/][company-irony]] 基于 irony 提供补全功能。

#+BEGIN_SRC emacs-lisp
  (use-package company-irony
    :ensure t
    :after (company irony)
    :init
    (add-to-list 'company-backends 'company-irony))
#+END_SRC

* Debugging

#+BEGIN_SRC emacs-lisp
  (setq
   ;; 缺省激活 gdb-many-windows
   gdb-many-windows t

   ;; 启动的时候显示包含 main 的源文件
   gdb-show-main t)
#+END_SRC

* 参考资料

  - [[https://tuhdo.github.io/c-ide.html][Setup C/C++ Development Environment for Emacs - tuhdo]] 经典的文章，
    使用 ggtags、helm、company、CEDET、projectile、hs-minor-mode 等
  - [[https://github.com/mawenbao/emacs.d][awenbao/emacs.d]] 以上文为基础配置的 C/C++、Golang 和 Python 的开发
    环境
  - [[http://syamajala.github.io/c-ide.html][Emacs as C++ IDE - syamajala]] 基于 tuhdo 的文章做了一些改进，主要是
    rtags、irony、cmake-ide
  - [[https://trivialfis.github.io/emacs/2017/08/02/C-C%2B%2B-Development-Environment-on-Emacs.html][C/C++ Development Environment for Emacs - Trivial Fis]] 使用
    cmake-ide、irony、rtags、semantic、ECB、disaster、projectile 等
  - [[https://vxlabs.com/2016/04/11/step-by-step-guide-to-c-navigation-and-completion-with-emacs-and-the-clang-based-rtags/][C++ navigation and completion with Emacs and the Clang-based rtags]]
    使用 rtags
  - [[https://github.com/redguardtoo/mastering-emacs-in-one-year-guide/blob/master/emacs_cpp_developer_guide-en.org][Practical Emacs Guide for C++ developers]]
  - [[http://nilsdeppe.com/posts/emacs-c%2B%2B-ide][Using Emacs as a C++ IDE - Nils]] 使用 flycheck、cmake-ide、rtags、
    Helm、Irony、Semantic、flyspell 配置 C++ IDE，在一年多后的 [[http://nilsdeppe.com/posts/emacs-c%2B%2B-ide2][Take 2]]
    中因为性能问题改为 Ivy/Swiper、counsel-etags、ClangFormat、
    ycmd/emacs-ycmd 等
  - [[https://oremacs.com/2017/03/28/emacs-cpp-ide/][Using Emacs as a C++ IDE - or emacs]] 用 rtags 跳转，用 irony 补全
  - [[http://martinsosic.com/development/emacs/2017/12/09/emacs-cpp-ide.html][Emacs as a C++ IDE - Martin Sosic]] 使用 Company、Flycheck、Irony、
    RTags、Projectile 和 Helm；用 Bear 生成 Compilation Database，
    用.clang_complete 让 Irony 支持头文件；因为 Rtags 比 Irony 慢，所
    以小项目用 Rtags，大项目用 Irony
  - [[https://maskray.me/blog/2017-12-03-c%2B%2B-language-server-cquery][使用 cquery：C++ language server]]
  - [[https://github.com/redguardtoo/cpputils-cmake][redguardtoo/cpputils-cmake: Easy real time C++ syntax check and
    intellisense if you use CMake]] 基于 CMake 的 C/C++ 开发环境的配置
  - [[https://emacs.stackexchange.com/questions/474/using-emacs-as-a-full-featured-c-c-ide/][Using Emacs as a full-featured C/C++ IDE - Emacs Stack Exchange]] 一
    些讨论，可以参考一下
  - [[https://github.com/emacs-tw/awesome-emacs][Awesome Emacs]] 推荐的扩展
    - CC Mode
    - rtags
    - ggtags
    - irony-mode
    - cmake-font-lock
    - function-args
    - Ebrowse
  - Spacemacs 使用的扩展
    - flycheck
    - disaster
    - clang-format
    - Semantic
    - cscope
    - company-clang
    - company-ycmd

